SET maintenance_work_mem = '2GB';
CREATE INDEX IF NOT EXISTS asset_registry_asset_id ON sm.asset_registry (asset_id);
CREATE INDEX IF NOT EXISTS mv_swaps_row_id ON sm.mv_swaps (_row_id);
CREATE INDEX IF NOT EXISTS mv_transfers_row_id ON sm.mv_transfers (_row_id);
CREATE INDEX IF NOT EXISTS mv_bridges_row_id ON sm.mv_bridges (_row_id);
CREATE INDEX IF NOT EXISTS mv_fees_row_id ON sm.mv_fees (_row_id);
CREATE INDEX IF NOT EXISTS mv_extrinsics_row_id ON sm.mv_extrinsics (_row_id);
CREATE INDEX IF NOT EXISTS mv_liquidity_events_row_id ON sm.mv_liquidity_events (_row_id);
CREATE INDEX IF NOT EXISTS mv_order_book_events_row_id ON sm.mv_order_book_events (_row_id);
CREATE INDEX IF NOT EXISTS fee_burns_live_block ON sm.fee_burns_live (block_height);
CREATE INDEX IF NOT EXISTS val_staking_rewards_id ON sm.val_staking_rewards (id);
CREATE INDEX IF NOT EXISTS supply_snapshots_id ON sm.supply_snapshots (id);
CREATE INDEX IF NOT EXISTS price_history_key ON sm.price_history (asset_id, hour_bucket);
CREATE INDEX IF NOT EXISTS supply_history_key ON sm.supply_history (symbol, timestamp);
CREATE INDEX IF NOT EXISTS asset_snapshot_key ON public.asset_snapshot (asset_id, timestamp);
CREATE INDEX IF NOT EXISTS site_events_id ON sm.site_events (id);
CREATE INDEX IF NOT EXISTS polkamarkt_markets_id ON sm.polkamarkt_markets (market_id);
CREATE INDEX IF NOT EXISTS polkamarkt_trades_id ON sm.polkamarkt_trades (id);
CREATE INDEX IF NOT EXISTS polkamarkt_claims_id ON sm.polkamarkt_claims (id);
CREATE INDEX IF NOT EXISTS polkamarkt_buybacks_id ON sm.polkamarkt_buybacks (id);
CREATE INDEX IF NOT EXISTS polkamarkt_burns_id ON sm.polkamarkt_burns (id);
CREATE INDEX IF NOT EXISTS news_episodes_slug ON sm.news_episodes (slug);
ANALYZE sm.mv_swaps; ANALYZE sm.mv_transfers; ANALYZE sm.mv_bridges; ANALYZE sm.mv_fees; ANALYZE sm.mv_extrinsics;
ANALYZE sm.mv_liquidity_events; ANALYZE sm.mv_order_book_events; ANALYZE sm.fee_burns_live; ANALYZE sm.val_staking_rewards;
ANALYZE sm.supply_snapshots; ANALYZE sm.price_history; ANALYZE sm.supply_history; ANALYZE public.asset_snapshot; ANALYZE sm.site_events;
CREATE INDEX IF NOT EXISTS extrinsic_events_block_idx ON sm.extrinsic_events (block_height, extrinsic_index);
ANALYZE sm.extrinsic_events; ANALYZE public.history_element;
